<a href="https://colab.research.google.com/github/laurafoes/extensao--python-pandas/blob/main/primeiro-exemplo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_excel("ca-2021-02.xlsx")

In [7]:
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [8]:
#Exibe as primeiras 5 linhas
display(combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [9]:
# Quero, na verdade, exibir as primeiras 15 linhas
display(combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [10]:
#retorna os dados da tabela
print(combustiveis_df.shape)

(168409, 16)

In [11]:
print(combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [12]:
#Quais são as colunas e que tipo de dados cada um tem...
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [13]:
#filtrar por uma COLUNA
display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [14]:
#Cria dataframe apenas com as colunas desejadas
ca_df = combustiveis_df[['Revenda', 'Produto', 'Municipio', 'Valor de Venda']] 
display(ca_df)

,Revenda,Produto,Municipio,Valor de Venda
0,POSTO ARAPIRACA LTDA,GASOLINA,ARAPIRACA,6.799
1,POSTO ARAPIRACA LTDA,ETANOL,ARAPIRACA,5.299
2,POSTO ARAPIRACA LTDA,DIESEL,ARAPIRACA,5.549
3,POSTO ARAPIRACA LTDA,GASOLINA ADITIVADA,ARAPIRACA,6.899
4,POSTO ARAPIRACA LTDA,DIESEL S10,ARAPIRACA,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,ETANOL,JEQUIE,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,GASOLINA,ITUIUTABA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ETANOL,ITUIUTABA,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,DIESEL S10,ITUIUTABA,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,GASOLINA ADITIVADA,ITUIUTABA,6.580

In [15]:
#Exibe a 4a. linha.
display(ca_df.loc[3])

Revenda           POSTO ARAPIRACA LTDA
Produto             GASOLINA ADITIVADA
Municipio                    ARAPIRACA
Valor de Venda                   6.899
Name: 3, dtype: object

In [16]:
#Exibir da 10a. linha até a 20a.linha
display(ca_df.loc[9:19])

,Revenda,Produto,Municipio,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DIESEL S10,DELMIRO GOUVEIA,5.983
10,AUTO POSTO DA PEDRA LTDA,GASOLINA,DELMIRO GOUVEIA,7.197
11,AUTO POSTO DA PEDRA LTDA,ETANOL,DELMIRO GOUVEIA,5.987
12,AUTO POSTO DA PEDRA LTDA,DIESEL,DELMIRO GOUVEIA,5.978
13,AUTO POSTO DA PEDRA LTDA,DIESEL S10,DELMIRO GOUVEIA,5.989
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,GASOLINA,DELMIRO GOUVEIA,7.175
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,ETANOL,DELMIRO GOUVEIA,5.930
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DIESEL,DELMIRO GOUVEIA,5.955
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,GASOLINA ADITIVADA,DELMIRO GOUVEIA,7.175
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DIESEL S10,DELMIRO GOUVEIA,5.980
19,MARCOS ANTONIO DA SILVA CABRAL,GASOLINA,ITACOATIARA,6.990

In [19]:
#Cria o dataframe gas_df contendo: 
#4 colunas (revenda, mun, produto e valor de venda)
#somente com combustível do tipo GASOLINA
#exibir resultado na tela

gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

,Revenda,Produto,Municipio,Valor de Venda
0,POSTO ARAPIRACA LTDA,GASOLINA,ARAPIRACA,6.799
5,AUTO POSTO FREITAS & MAIA LTDA,GASOLINA,DELMIRO GOUVEIA,7.198
10,AUTO POSTO DA PEDRA LTDA,GASOLINA,DELMIRO GOUVEIA,7.197
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,GASOLINA,DELMIRO GOUVEIA,7.175
19,MARCOS ANTONIO DA SILVA CABRAL,GASOLINA,ITACOATIARA,6.990
...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,GASOLINA,BAURU,6.199
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,GASOLINA,ITUIUTABA,6.899
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,GASOLINA,CAMPOS DOS GOYTACAZES,7.090
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,GASOLINA,JEQUIE,6.799
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,GASOLINA,ITUIUTABA,6.580

7.999

In [20]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Filtrar quais os preços e postos que vendem combustível do tipo ETANOL em Indaiatuba
#Ordenado do menor valor de venda para o maior

etanol_indaiatuba_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'INDAIATUBA')]
display(etanol_indaiatuba_df.sort_values(by='Valor de Venda'))

,Revenda,Produto,Municipio,Valor de Venda
160592,AUTO POSTO NAMORADA II LTDA.,ETANOL,INDAIATUBA,4.679
140194,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,ETANOL,INDAIATUBA,4.679
140661,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,ETANOL,INDAIATUBA,4.699
159497,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,ETANOL,INDAIATUBA,4.699
141167,AUTO POSTO ESPLANADA DE INDAIA LTDA,ETANOL,INDAIATUBA,4.699
...,...,...,...,...
51129,AUTO POSTO CIDADE DO SOL II LTDA,ETANOL,INDAIATUBA,5.599
51138,AUTO POSTO NAMORADA II LTDA.,ETANOL,INDAIATUBA,5.599
84395,AUTO POSTO NAMORADA II LTDA.,ETANOL,INDAIATUBA,5.599
65878,AUTO POSTO CIDADE DO SOL II LTDA,ETANOL,INDAIATUBA,5.599
65363,AUTO POSTO INDIANA SELF LTDA.,ETANOL,INDAIATUBA,6.197

In [21]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?

display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [22]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
# Utulizando o método .isin()
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [23]:
# Média de valor de venda POR COMBUSTÍVEL em todo o país?
media_por_combustivel_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel_df)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [24]:
#Quero adicionar uma coluna de valor booleano no combustiveis_df
# chamada "Ativo" que, por padrão, vai ser True para 
# TODAS as linhas
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [28]:
# E se eu quiser uma coluna nova chamada "Obs"
# que preencha automaticamente "MELHOR CIDADE"
# quando o Município for INDAIATUBA, SP...
#combustiveis_df['Obs'] = "MELHOR CIDADE" if combustiveis_df['Municipio'] == "INDAIATUBA" else ""

In [25]:
# Exportar para Excel o dataframe com etanol em Indaiatuba....
etanol_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')